include $(GOROOT)/src/Make.inc

TARG=goweb
GOFILES=\
  constants.go \
	parameter_key_map.go \
	parameter_value_map.go \
	requests.go \
	standard_response.go \
	context.go \
	path_parsing.go \
	controller.go \
	rest_controller.go \
	route_matching.go \
	route.go \
	route_manager.go \
	http_handler.go \
	shortcut_funcs.go \
	formatters.go

include $(GOROOT)/src/Make.pkg
